name: Update Alpine base image
on:
  workflow_call:
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_TOKEN:
        required: true
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: echo Updating images relying on base Alpine image...
