name: Ship alpine-gui-java image
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Ship alpine-gui image
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - 'docker/images/alpine-gui-java/**'
jobs:
  release_image:
    uses: ./.github/workflows/release_image.yaml
    with:
      image: alpine-gui-java
    secrets: inherit
