name: Ship alpine-gui-java image
on:
  workflow_call:
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_TOKEN:
        required: true
  workflow_run:
    workflows:
      - Ship alpine-gui image
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - 'docker/images/alpine-gui-java/**'
jobs:
  release_image:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Release image
        uses: ./.github/workflows/release_image.yaml
        with:
          dockerfile-dir: alpine-gui-java
        secrets: inherit
