name: Ship alpine-gui-javafx image
on:
  workflow_call:
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_TOKEN:
        required: true
  workflow_run:
    workflows:
      - Ship alpine-gui-java image
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - 'docker/images/alpine-gui-javafx/**'
jobs:
  release_image:
    uses: ./.github/workflows/release_image.yaml
    with:
      image: alpine-gui-javafx
    secrets: inherit
