name: Ship alpine-java image
on:
  workflow_call:
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_TOKEN:
        required: true
  workflow_run:
    workflows:
      - Update Alpine base image
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - 'docker/images/alpine-java/**'
jobs:
  release_image:
    uses: ./.github/workflows/release_image.yaml
    with:
      image: alpine-java
    secrets: inherit
