name: Ship alpine-angular image
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Update Alpine base image
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - 'docker/images/alpine-angular/**'
jobs:
  release_image:
    uses: ./.github/workflows/release_image.yaml
    with:
      image: alpine-angular
    secrets: inherit
