name: Release basic Docker images
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docker/images/Alpine**'
      - '!docker/images/Alpine-GUI**'
      - '!docker/images/Alpine-Java-WinPack**'

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Alpine-Java
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/images/Alpine-Java/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/alpine-java:latest
