name: Ship jupyter-ml image
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docker/images/jupyter-ml/**'
jobs:
  release_image:
    uses: ./.github/workflows/release_image.yaml
    with:
      image: jupyter-ml
    secrets: inherit
