name: Build and push image to Docker Hub
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    secrets:
      DOCKER_USER:
        description: 'Username on DockerHub'
        required: true
      DOCKER_TOKEN:
        description: 'App password on DockerHub'
        required: true
jobs:
  ship_to_docker_hub:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: docker/images/${{ inputs.image }}
          file: docker/images/${{ inputs.image }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ inputs.image }}:latest
